name: Ruby CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7.5', '3.0.3', '3.1.0']
        appraisal: ['rails_6.1', 'rails_7.0']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      run: |
        gem install bundler:2.3.6
        bundle install --jobs 4 --retry 3

    - name: Run tests
      run: |
        bundle exec appraisal ${{ matrix.appraisal }} rake test